name: Publish package to pub.dev
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - uses: dart-lang/setup-dart@v1

      - run: flutter --version

      - run: flutter pub get

      - run: dart format --set-exit-if-changed .

      - run: flutter analyze --verbose

      - name: Run tests
        run: flutter test --coverage --test-randomize-ordering-seed=$RANDOM

      - name: Generate coverage report
        run: genhtml coverage/lcov.info -o coverage/html

      - uses: actions/upload-artifact@v4
        with:
          name: coverate-report
          path: coverage/html

      - name: Publish package
        run: flutter pub publish --force
