name: Publish package to pub.dev
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - run: dart --version

      - run: dart pub get

      - run: dart format --set-exit-if-changed .

      - run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test --test-randomize-ordering-seed=random

      - name: Publish package
        run: dart pub publish --force
